controller_list:
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - LeftShoulderRoll
      - LeftShoulderYaw
      - LeftElbowPitch
      - LeftElbowYaw
      - LeftWristPitch
      - LeftWristRoll
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - RightShoulderRoll
      - RightShoulderYaw
      - RightElbowPitch
      - RightElbowYaw
      - RightWristPitch
      - RightWristRoll
  - name: left_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - LeftLegRoll
      - LeftLegYaw
      - kneePitch
      - AnklePitch
      - AnkleRoll
  - name: right_leg_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - RightLegRoll
      - RightLegYaw
      - RkneePitch
      - RAnklePitch
      - RAnkleRoll
  - name: neck_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - NeckRoll
      - NeckPitch
  - name: upper_body_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - LeftShoulderRoll
      - LeftShoulderYaw
      - LeftElbowPitch
      - LeftElbowYaw
      - LeftWristPitch
      - LeftWristRoll
      - NeckRoll
      - NeckPitch
      - RightShoulderRoll
      - RightShoulderYaw
      - RightElbowPitch
      - RightElbowYaw
      - RightWristPitch
      - RightWristRoll
  - name: whole_body_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - LeftShoulderRoll
      - LeftShoulderYaw
      - LeftElbowPitch
      - LeftElbowYaw
      - LeftWristPitch
      - LeftWristRoll
      - NeckRoll
      - NeckPitch
      - RightShoulderRoll
      - RightShoulderYaw
      - RightElbowPitch
      - RightElbowYaw
      - RightWristPitch
      - RightWristRoll
      - LeftLegRoll
      - LeftLegYaw
      - kneePitch
      - AnklePitch
      - AnkleRoll
      - RightLegRoll
      - RightLegYaw
      - RkneePitch
      - RAnklePitch
      - RAnkleRoll