  RightShoulderPitch:        rightarm_leg_r1_joint
  RightShoulderRoll:         rightarm_leg_r2_joint
  RightShoulderYaw:          rightarm_leg_r3_joint
  RightElbowPitch:           rightarm_leg_r4_joint
  RightElbowYaw:             rightarm_leg_r5_joint
  RightWristPitch:           rightarm_leg_r6_joint
  RightWristRoll:            rightarm_leg_r7_joint